builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 7

    ldflags:
      - >-
        -s
        -w
        -X github.com/macaroni-os/gpu-configurator/cmd.BuildTime={{.Date}}
        -X github.com/macaroni-os/gpu-configurator/cmd.BuildCommit={{.Commit}}

archives:
  - format: binary
    name_template: gpu-configurator-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^tests:'
      - '^scripts:'
      - '^contrib'
      - '^.github'
